### ISSUE TITLE
store clock.printToDate() / clock.printToTime() in a variable

### ISSUE THREAD

**Issue by AleixF** [sleemanj/DS3231_Simple#1]
hi, 
I am trying to store the value of clock.printToDate_DMY() and clock.printToTime_HM() in two variables, is this possible? 
I got print it in serial monitor but I don't know how store those values in a variable to be stored in a SD card.

**Comment by sleemanj** [comment]
See examples/z1_TimeAndDate/ReadDateTime

https://github.com/sleemanj/DS3231_Simple/blob/master/examples/z1_TimeAndDate/ReadDateTime/ReadDateTime.ino

once you have your data in MyDateAndTime you can do what you like with the Hour, Minute, Second etc as you please.
