### ISSUE TITLE
How can i set alarm like 19:03:00 everyday

### ISSUE THREAD

**Issue by hcjplj** [sleemanj/DS3231_Simple#18]
first, Thank you to your library

I want to set alarm like 19:03:00 and 19:05:00 everyday

I want to turn on servo motor 1 at first alarm
and turn off at second alarm

Could you show me how to set alarm at special hour, minute, second?
How can i change this code?

`  DateTime MyTimestamp = Clock.read();              
  
  // We want the alarm at this second
  MyTimestamp.Second  = 30;                       
  MyTimestamp.Minute  = 3;
  
  // And now add the alarm to happen when the second matches
  Clock.setAlarm(MyTimestamp, DS3231_Simple::ALARM_MATCH_SECOND); 
  Clock.setAlarm(MyTimestamp, DS3231_Simple::ALARM_MATCH_MINUTE_HOUR); `

**Comment by sleemanj** [comment]
Please read comments at 
 bottom of https://github.com/sleemanj/DS3231_Simple/blob/master/examples/z2_Alarms/Alarm/Alarm.ino
which explains how the alarms function.
