### ISSUE TITLE
Clock doesn't tick

### ISSUE THREAD

**Issue by Gerengnick** [sleemanj/DS3231_Simple#19]
Hello,

I'm relatively new to arduino and especially interacting with the RTC. I ran the hello world example sketch, as well as tried out the set time and read time, and no matter what I have done, the clock is static in the time I set. The Hello world sketch is not giving the right time. It has taken over a minute for the clock to progress even a second. Is this a known issue I just can't seem to find?

**Comment by Gerengnick** [comment]
It is about 85 real seconds per RTC second.

**Comment by sleemanj** [comment]
Sounds like your RTC may be faulty.
