### ISSUE TITLE
Error - Import library on Arduino IDE 2.2.1

### ISSUE THREAD

**Issue by RogerLTx** [sleemanj/DS3231_Simple#26]
Steps followed: Sketch\Include Library\Add .ZIP Library and the error message appears:
"Error 13 Internal. Library installed failed: archive is not valid: multiple files found in ZIP file top level."

**Comment by sleemanj** [comment]
Try the attached
[DS3231_Simple.zip](https://github.com/sleemanj/DS3231_Simple/files/12705321/DS3231_Simple.zip)

**Comment by RogerLTx** [comment]
Hi.
Thank you for your answer.
Same error
***@***.***

***@***.***

Rogerio

De: James Sleeman ***@***.***>
Enviada em: sexta-feira, 22 de setembro de 2023 22:25
Para: sleemanj/DS3231_Simple ***@***.***>
Cc: RogerLTx ***@***.***>; Author ***@***.***>
Assunto: Re: [sleemanj/DS3231_Simple] Error - Import library on Arduino IDE 2.2.1 (Issue #26)


Try the attached
DS3231_Simple.zip<https://github.com/sleemanj/DS3231_Simple/files/12705321/DS3231_Simple.zip>

**Comment by sleemanj** [comment]
Sorry error in previous zip archive, this one is tested in 2.2.1 working
[DS3231_Simple.zip](https://github.com/sleemanj/DS3231_Simple/files/12708191/DS3231_Simple.zip)

**Comment by RogerLTx** [comment]
Oh! Don’t be sorry.
I appreciate your patience and support.
Everything is working now!

Thank you.

Rogerio

De: James Sleeman ***@***.***>
Enviada em: domingo, 24 de setembro de 2023 06:41
Para: sleemanj/DS3231_Simple ***@***.***>
Cc: RogerLTx ***@***.***>; Author ***@***.***>
Assunto: Re: [sleemanj/DS3231_Simple] Error - Import library on Arduino IDE 2.2.1 (Issue #26)


Sorry error in previous zip archive, this one is tested in 2.2.1 working
DS3231_Simple.zip<https://github.com/sleemanj/DS3231_Simple/files/12708191/DS3231_Simple.zip>
